# Generated by Django 4.1.5 on 2023-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(max_length=50, null=True, verbose_name='Deneme Yeri'),
        ),
    ]
