# Generated by Django 4.1.5 on 2023-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat'),
        ),
    ]
