# Generated by Django 4.1.5 on 2023-03-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_card_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deeneme',
            field=models.CharField(max_length=50, null=True, verbose_name='Deneme'),
        ),
    ]
