# Generated by Django 4.1.5 on 2023-03-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
