# Generated by Django 4.1.5 on 2023-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_alter_card_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Göster'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(default='logo.jpg', upload_to='', verbose_name='Resim'),
        ),
    ]
